<?php
/* @var $this Zend\View\Renderer\PhpRenderer  */
/* @var $accordion \ZF2Components\View\Component\AccordionContent */
$accordion = $this->accordion_content;
$contents = $accordion->getContents();
/** @var $content ZF2Components\View\Component\AccordionContent\Content */
echo $this->headScript()->appendFile($this->basePath().'/js/accordion.js');
echo $this->headLink()->appendStylesheet($this->basePath().'/css/accordion.css');

$jsObjectName = 'accordian_'.$accordion->getId(false);
?>

<div class="accordion-content-container">

	<script>
		var <?php echo $jsObjectName; ?> = new Accordion();
	</script>

	<?php echo $this->form()->openTag($this->form); ?>

	<div class="tabs">
		<ul class="nav nav-pills nav-stacked">
			<?php foreach($contents as $contentId => $content): ?>
				<li role="presentation" tab-selector="<?php echo $contentId; ?>">
					<a onclick="<?php echo $jsObjectName; ?>.showTab('<?php echo $contentId; ?>');">
						<?php echo $content->getTabLabel() ?>
					</a>
				</li>
				<script><?php echo $jsObjectName; ?>.addTab(
						'<?php echo $contentId; ?>',
						'<?php echo $content->getTabContentUrl(); ?>',
						<?php echo ($content->isAlwaysRefreshTabContentOnSelect())? 'true' : 'false'; ?>
					);
				</script>
			<?php endforeach; ?>
		</ul>
	</div>

	<?php foreach($contents as $contentId => $content): ?>
		<div class="content" tab-content="<?php echo $contentId; ?>"></div>
	<?php endforeach; ?>
	<div style="clear: both;"></div>

	<?php echo $this->form()->closeTag($this->form); ?>

	<script>
		$('document').ready(function(){
			<?php echo $jsObjectName; ?>.render();
		});
	</script>
</div>